{
 "title": "Сведения о размерах контейнеров и томов",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Размер контейнеров пользователей юпитер хаба",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container) (container_disk_usage_bytes{container=~\".*jupyter.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Размер контейнеров полный",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_disk_usage_bytes) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Размеры томов докера",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (image_disk_usage_bytes) by (image)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}