{
 "title": "JupyterHub сведения о контейнерах",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Процент использования CPU контейнерами",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (irate(container_cpu_user_seconds_total{name=~\".*jupyter.*\"}[5m])) * 100",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Активные пользователи за последние 24 часа",
   "type": "stat",
   "description": "Current number of active users",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jupyterhub_active_users{period=\"24h\"}"
    }
   ]
  },
  {
   "title": "Текущее использование памяти (RAM)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".*jupyter.*\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Всего зарегистрированных пользователей",
   "type": "stat",
   "description": "Time series plot of number of registered users",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jupyterhub_total_users{}", "legendFormat": "Total number of users" }
   ]
  },
  {
   "title": "Запущено контейнеров",
   "type": "stat",
   "description": "Current number of running servers",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jupyterhub_running_servers{}" }
   ]
  },
  {
   "title": "Количество остановок серверов JupyterHub",
   "type": "stat",
   "description": "Average number of server stops by their status",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(jupyterhub_server_stop_seconds_count{}[$__range])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Вычисляет скорость изменения использования CPU за последние 5 минут",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".*jupyter.*\"}[5m])) by (name) * 100 / 4",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общий размер файловой системы контейнера (не включая слои образа)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{name=~\".*jupyter.*\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Входы по SSH на сервер всего",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ssh_login_attempt_info) by (username)",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}