{
 "title": "Использование GPU",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Использоdание GPU сервисами",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(gpu_process_memory_usage) by (process_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gpu_utilization%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_utilization{job=\"node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gpu_memory_total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_memory_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "gpu_memory_used ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_memory_used ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Температура GPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gpu_process_memory_usage) by (process_name)",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}