{
 "title": "Сведения PostgresQL",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "БД общий размер",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_database_size_mb) by (database)",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Размер таблиц в базе данных",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(pg_table_size_bytes) by (table_name, owner))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общее количество последовательных сканирований",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (pg_table_seq_scan_total) by (table_name) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общее количество кортежей, прочитанных при последовательном сканировании",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (pg_table_seq_tup_read_total) by (table_name) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}